spring:
  application:
    name: QuotesApp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movieQuotes?currentSchema=quotes
    username: postgres
    password: postgres
server:
  port: 8083